resource_types:

resources:
  - name: spring-boot-sample
    type: git
    source:
      uri: https://github.com/gguptahcl/springboot-sample.git
      branch: master

jobs:
  - name: unit-tests
    public: true
    plan:
      - get: spring-boot-sample
        trigger: true
      - task: mvn-test
        config:
              platform: linux
              image_resource:
                type: docker-image
                source: 
                  repository: java
                  tag: openjdk-8
              outputs:
                - name: spring-boot-sample-unit-test-output
              run:
                path: springboot-sample/concourse_ci/tasks/maventest.sh