---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

inputs:
  - name: spring-boot-sample

run:
  path: "mvn"
  args:
    - -f
    - spring-boot-sample/pom.xml
    - clean
    - package
    
outputs:
  - name: spring-boot-sample-out
    path: spring-boot-sample
