---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8

inputs:
  - name: spring-boot-sample

outputs:
  - name: spring-boot-sample-unit-test-output
#   path: spring-boot-sample


#run:
#  path: "mvn"
#  args:
#    - -f
#    - spring-boot-sample/pom.xml
#    - clean
#    - test

run:
  path: /bin/sh
  args: ["spring-boot-sample/concourse_ci/tasks/maventest.sh"]
  
  
