---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: alpine}

inputs:
  - name: spring-boot-sample
  - name: spring-boot-sample-unit-test-output

outputs:
  - name: sonar-scan-output

run:
  #path: spring-boot-sample/concourse_ci/tasks/sonarscan.sh
  path: /bin/sh
  args: ["spring-boot-sample/concourse_ci/tasks/sonarscan.sh"]
  
  