---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8

#inputs:
#  - name: spring-boot-sample
#  - name: spring-boot-sample-unit-test-output

outputs:
  - name: sonar-scan-output

run:
  path: /bin/sh
  args: ["spring-boot-sample/concourse_ci/tasks/maventest.sh"]
  
  